config/routes.rb
Rails.application.routes.draw do
  resources :wishes
  root 'dashboard#index'
end

app/models/wish.rb
class Wish < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  def new
  end

  def show
    @wish = Wish.find(params[:id])
  end

  def index
    @wishes = Wish.all
  end

  def create
    @wish = Wish.new(post_params)

    @wish.save
    redirect_to @wish
  end

  private
  def post_params
    params.require(:wish).permit(:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/dashboard/index.html.erb
<h1>iwishfor - Top Wishes</h1>

<ol>
  <li>Wish 1</li>
  <li>Wish 2</li>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>I wish for ...</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/wishes/index.html.erb
<h1>Listing wishes</h1>

<%= link_to 'New wish', new_wish_path %>
<table>
  <tr>
    <th>Description</th>
  </tr>

  <% @wishes.each do |wish| %>
    <tr>
      <td><%= wish.description %></td>
    </tr>
  <% end %>
</table>

app/views/wishes/new.html.erb
<%= form_for :wish, url: wishes_path do |f| %>
    <p>
      <%= f.label :description %><br>
      <%= f.text_field :description %>
    </p>
    <p>
      <%= f.submit %>
      </p>
<% end %>
<%= link_to 'Back', wishes_path %>

app/views/wishes/show.html.erb
<p>
  <strong>Description:</strong>
  <%= @wish.description %>
</p>
<%= link_to 'Back', wishes_path %>